### ISSUE TITLE
get runtime exception when running neural network model 

### ISSUE THREAD

**Issue by luojijiaren** [open-datastudio/zeppelin#10]
I tried to run word2vec (a popular neural network model in NLP), and got the runtime exception error. see below for more detail: 
![image](https://user-images.githubusercontent.com/18145176/90356580-e124d580-e004-11ea-85a8-f939cadd0448.png)

**Comment by luojijiaren** [comment]
this issue is not urgent :)

**Comment by Leemoonsoo** [comment]
You can see this error message when the Zeppelin server is disconnected from the interpreters.
However, it does not shows why it is disconnected. Log message from interpreter sometimes helps to understand why it is disconnected. You can see log messages from all interpreter by click 'logs' link from staroid.

![image](https://user-images.githubusercontent.com/1540981/90407486-70f56e80-e05b-11ea-9f41-82edbc5d8da3.png)


There can be many different reasons for disconnection, but one of the common reasons is interpreter crashes for some reason. And Out Of Memory error is the common reason for crash. If you think this is the case, you can increase memory for pyspark in local mode by setting `spark.driver.memory` (default 8g) like

```
%spark.conf
spark.master local[*]
spark.driver.memory 16g
```

In cluster mode, you can change executor memory `spark.executor.memory` and staroid instance-type correspond to it. Like

```
%spark.conf
spark.executor.memory 16g
spark.kubernetes.executor.label.pod.staroid.com/instance-type standard-4
```
