### ISSUE TITLE
Can I upload and store data within the cluster, and read it from python?

### ISSUE THREAD

**Issue by luojijiaren** [open-datastudio/zeppelin#8]
I just started trying Zeppelin here. I don't want to store data in S3 or my remote repository. Is it possible to upload the data files and store them within the cluster?

**Comment by Leemoonsoo** [comment]
All interpreters in [open-datastudio/zeppelin](https://github.com/open-datastudio/zeppelin) are running inside its own [Pod](https://kubernetes.io/docs/concepts/workloads/pods/). And all interpreter Pods mount the same NFS volume under `/data` directory. So, any data stored in `/data` will accessible from `%python` interpreter.

To upload files to `/data` directory, you start a file browser for `data-pvc` Volume.

![image](https://user-images.githubusercontent.com/1540981/90338965-5ad7a780-dfa2-11ea-813c-0c6d097aff05.png)

Once started, you can click `browse` link and open file browser. 
![image](https://user-images.githubusercontent.com/1540981/90339002-a7bb7e00-dfa2-11ea-95a4-5cd9346f6896.png)

You'll able to upload/download files using it. Once file is uploaded, you can verify your file is accessible from Python interpreter, like

```
%python
!ls -al /data
```

Hope this helps.
