### ISSUE TITLE
In Spark tutorial 3. Spark SQL (PySpark), the "people.json" not exist

### ISSUE THREAD

**Issue by luojijiaren** [open-datastudio/zeppelin#9]
I'm trying the Spark tutorial 3. Spark SQL (PySpark), in the "Create DataFrame via DataFrameReader" paragraph, I got the "people.json" not exist issue

**Comment by Leemoonsoo** [comment]
The tutorial notebook included tries to access the example data from Spark installation path.
However, `%pyspark` in [open-datastudio/zeppelin](https://github.com/open-datastudio/zeppelin) runs Spark in a cluster mode by default. That means Spark executor(s) will run in separate Pods and they can't read example data while the path to example data is not distributed file systems such as hdfs or S3.

Two ways to make it work

a) Prepare example data on distributed filesystem like s3 and change code to point the s3 location.
b) Or, if you just want to try a tutorial notebook and don't really need distributed computing, you can set Spark local mode. Then the example data will be accessible from Spark installation path. To configure Spark local mode,

You can add a paragraph in your notebook and change `spark.master` property to `local[*]`
```
%spark.conf
spark.master local[*]
```

And run `%pyspark` with example data access will allow you access the data.
```
%pyspark
// run your tutorial
```

Note that `%spark.conf` paragraph must run before `%pyspark`. The best way to make sure this is restart interpreter and then run `%spark.conf`.

You can restart `%spark` interpreter from Zeppelin ui. See following screenshot.
![image](https://user-images.githubusercontent.com/1540981/90339253-73e15800-dfa4-11ea-8aab-f73af0c49baa.png)

**Comment by Leemoonsoo** [comment]
This tutorial notebook is from apache/zeppelin unmodified. It can really confuse if it does not work in open-datastudio/zeppelin out of the box. open-datastudio/zeppelin better keep tutorial notebooks works out of the box.

Let me work on this.
